// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TCClaCorrRecord struct {
	_             structs.HostLayout
	Cookie        uint64
	WindowStartNs uint64
	Net           TCClaFlowStats
	Proc          struct {
		_            structs.HostLayout
		Pid          uint32
		Uid          uint32
		Comm         [16]int8
		SyscallCount uint64
		ExecveCount  uint64
		MmapCount    uint64
	}
	LayerCoverage uint8
	Pad           [7]uint8
}

type TCClaFlowKey struct {
	_       structs.HostLayout
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	Pad     [3]uint8
}

type TCClaFlowStats struct {
	_            structs.HostLayout
	PktCount     uint64
	ByteCount    uint64
	LastSeenNs   uint64
	FirstSeenNs  uint64
	SynCount     uint32
	RstCount     uint32
	FinCount     uint32
	TcpFlagsSeen uint32
	IatSumNs     uint64
}

// LoadTC returns the embedded CollectionSpec for TC.
func LoadTC() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TCBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TC: %w", err)
	}

	return spec, err
}

// LoadTCObjects loads TC and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TCObjects
//	*TCPrograms
//	*TCMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTCObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTC()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TCSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TCSpecs struct {
	TCProgramSpecs
	TCMapSpecs
	TCVariableSpecs
}

// TCProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TCProgramSpecs struct {
	TcCorrelate *ebpf.ProgramSpec `ebpf:"tc_correlate"`
}

// TCMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TCMapSpecs struct {
	CookieMap     *ebpf.MapSpec `ebpf:"cookie_map"`
	CorrWindowMap *ebpf.MapSpec `ebpf:"corr_window_map"`
	FlowStatsMap  *ebpf.MapSpec `ebpf:"flow_stats_map"`
	RingEvents    *ebpf.MapSpec `ebpf:"ring_events"`
}

// TCVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TCVariableSpecs struct {
}

// TCObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTCObjects or ebpf.CollectionSpec.LoadAndAssign.
type TCObjects struct {
	TCPrograms
	TCMaps
	TCVariables
}

func (o *TCObjects) Close() error {
	return _TCClose(
		&o.TCPrograms,
		&o.TCMaps,
	)
}

// TCMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTCObjects or ebpf.CollectionSpec.LoadAndAssign.
type TCMaps struct {
	CookieMap     *ebpf.Map `ebpf:"cookie_map"`
	CorrWindowMap *ebpf.Map `ebpf:"corr_window_map"`
	FlowStatsMap  *ebpf.Map `ebpf:"flow_stats_map"`
	RingEvents    *ebpf.Map `ebpf:"ring_events"`
}

func (m *TCMaps) Close() error {
	return _TCClose(
		m.CookieMap,
		m.CorrWindowMap,
		m.FlowStatsMap,
		m.RingEvents,
	)
}

// TCVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTCObjects or ebpf.CollectionSpec.LoadAndAssign.
type TCVariables struct {
}

// TCPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTCObjects or ebpf.CollectionSpec.LoadAndAssign.
type TCPrograms struct {
	TcCorrelate *ebpf.Program `ebpf:"tc_correlate"`
}

func (p *TCPrograms) Close() error {
	return _TCClose(
		p.TcCorrelate,
	)
}

func _TCClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tc_bpfeb.o
var _TCBytes []byte
