// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TracepointClaCorrRecord struct {
	_             structs.HostLayout
	Cookie        uint64
	WindowStartNs uint64
	Net           struct {
		_            structs.HostLayout
		PktCount     uint64
		ByteCount    uint64
		LastSeenNs   uint64
		FirstSeenNs  uint64
		SynCount     uint32
		RstCount     uint32
		FinCount     uint32
		TcpFlagsSeen uint32
		IatSumNs     uint64
	}
	Proc          TracepointClaProcState
	LayerCoverage uint8
	Pad           [7]uint8
}

type TracepointClaProcState struct {
	_            structs.HostLayout
	Pid          uint32
	Uid          uint32
	Comm         [16]int8
	SyscallCount uint64
	ExecveCount  uint64
	MmapCount    uint64
}

// LoadTracepoint returns the embedded CollectionSpec for Tracepoint.
func LoadTracepoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracepointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Tracepoint: %w", err)
	}

	return spec, err
}

// LoadTracepointObjects loads Tracepoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TracepointObjects
//	*TracepointPrograms
//	*TracepointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTracepointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTracepoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TracepointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TracepointSpecs struct {
	TracepointProgramSpecs
	TracepointMapSpecs
	TracepointVariableSpecs
}

// TracepointProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TracepointProgramSpecs struct {
	TraceConnect *ebpf.ProgramSpec `ebpf:"trace_connect"`
}

// TracepointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TracepointMapSpecs struct {
	CorrWindowMap *ebpf.MapSpec `ebpf:"corr_window_map"`
	ProcStateMap  *ebpf.MapSpec `ebpf:"proc_state_map"`
	RingEvents    *ebpf.MapSpec `ebpf:"ring_events"`
}

// TracepointVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TracepointVariableSpecs struct {
}

// TracepointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracepointObjects struct {
	TracepointPrograms
	TracepointMaps
	TracepointVariables
}

func (o *TracepointObjects) Close() error {
	return _TracepointClose(
		&o.TracepointPrograms,
		&o.TracepointMaps,
	)
}

// TracepointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracepointMaps struct {
	CorrWindowMap *ebpf.Map `ebpf:"corr_window_map"`
	ProcStateMap  *ebpf.Map `ebpf:"proc_state_map"`
	RingEvents    *ebpf.Map `ebpf:"ring_events"`
}

func (m *TracepointMaps) Close() error {
	return _TracepointClose(
		m.CorrWindowMap,
		m.ProcStateMap,
		m.RingEvents,
	)
}

// TracepointVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracepointVariables struct {
}

// TracepointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTracepointObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracepointPrograms struct {
	TraceConnect *ebpf.Program `ebpf:"trace_connect"`
}

func (p *TracepointPrograms) Close() error {
	return _TracepointClose(
		p.TraceConnect,
	)
}

func _TracepointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracepoint_bpfeb.o
var _TracepointBytes []byte
