// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type XDPClaFlowKey struct {
	_       structs.HostLayout
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	Pad     [3]uint8
}

type XDPClaFlowStats struct {
	_            structs.HostLayout
	PktCount     uint64
	ByteCount    uint64
	LastSeenNs   uint64
	FirstSeenNs  uint64
	SynCount     uint32
	RstCount     uint32
	FinCount     uint32
	TcpFlagsSeen uint32
	IatSumNs     uint64
}

// LoadXDP returns the embedded CollectionSpec for XDP.
func LoadXDP() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XDPBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load XDP: %w", err)
	}

	return spec, err
}

// LoadXDPObjects loads XDP and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XDPObjects
//	*XDPPrograms
//	*XDPMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXDPObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXDP()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XDPSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XDPSpecs struct {
	XDPProgramSpecs
	XDPMapSpecs
	XDPVariableSpecs
}

// XDPProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XDPProgramSpecs struct {
	XdpFlowMonitor *ebpf.ProgramSpec `ebpf:"xdp_flow_monitor"`
}

// XDPMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XDPMapSpecs struct {
	FlowStatsMap *ebpf.MapSpec `ebpf:"flow_stats_map"`
}

// XDPVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XDPVariableSpecs struct {
}

// XDPObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type XDPObjects struct {
	XDPPrograms
	XDPMaps
	XDPVariables
}

func (o *XDPObjects) Close() error {
	return _XDPClose(
		&o.XDPPrograms,
		&o.XDPMaps,
	)
}

// XDPMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type XDPMaps struct {
	FlowStatsMap *ebpf.Map `ebpf:"flow_stats_map"`
}

func (m *XDPMaps) Close() error {
	return _XDPClose(
		m.FlowStatsMap,
	)
}

// XDPVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type XDPVariables struct {
}

// XDPPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type XDPPrograms struct {
	XdpFlowMonitor *ebpf.Program `ebpf:"xdp_flow_monitor"`
}

func (p *XDPPrograms) Close() error {
	return _XDPClose(
		p.XdpFlowMonitor,
	)
}

func _XDPClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_bpfeb.o
var _XDPBytes []byte
